def handleError(self, record):
    '\n        Handle an error during logging.\n\n        An error has occurred during logging. Most likely cause -\n        connection lost. Close the socket so that we can retry on the\n        next event.\n        '
    if (self.closeOnError and self.sock):
        self.sock.close()
        self.sock = None
    else:
        logging.Handler.handleError(self, record)
