def test_instanceWithException(self):
    self.assertRaises(TypeError, set, baditer())
