def test_try_except_finally(self):
    hit_except = False
    hit_finally = False
    try:
        try:
            raise Exception, 'yarr!'
        except:
            hit_except = True
    finally:
        hit_finally = True
    self.assertTrue(hit_except)
    self.assertTrue(hit_finally)
