def test_badfuture6(self):
    try:
        from test import badsyntax_future6
    except SyntaxError as msg:
        self.assertEqual(get_error_location(msg), ('badsyntax_future6', '3'))
    else:
        self.fail("expected exception didn't occur")
