def test_bad_address(self):
    self.assertRaises(IOError, urllib2.urlopen, 'http://www.python.invalid./')
