def test_bug_545855(self):
    self.assertRaises(re.error, re.compile, 'foo[a-')
